### ISSUE TITLE
(1049, "Unknown database 'spider'")

### ISSUE THREAD

**Issue by acgtyrant** [GuozhuHe/webspider#1]
不会 Web 开发，按 README 试着启动了下 `bin/web`, 访问 `127.0.0.1:8000` 出现错误：

```
Traceback (most recent call last):
  File "/home/acgtyrant/Projects/webspider/.env/lib/python3.6/site-packages/sqlalchemy/pool.py", line 1122, in _do_get
    return self._pool.get(wait, self._timeout)
  File "/home/acgtyrant/Projects/webspider/.env/lib/python3.6/site-packages/sqlalchemy/util/queue.py", line 145, in get
    raise Empty
sqlalchemy.util.queue.Empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/acgtyrant/Projects/webspider/.env/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 2147, in _wrap_pool_connect
    return fn()
  File "/home/acgtyrant/Projects/webspider/.env/lib/python3.6/site-packages/sqlalchemy/pool.py", line 387, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/acgtyrant/Projects/webspider/.env/lib/python3.6/site-packages/sqlalchemy/pool.py", line 766, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/acgtyrant/Projects/webspider/.env/lib/python3.6/site-packages/sqlalchemy/pool.py", line 516, in checkout
    rec = pool._do_get()
  File "/home/acgtyrant/Projects/webspider/.env/lib/python3.6/site-packages/sqlalchemy/pool.py", line 1138, in _do_get
    self._dec_overflow()
  File "/home/acgtyrant/Projects/webspider/.env/lib/python3.6/site-packages/sqlalchemy/util/langhelpers.py", line 66, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/home/acgtyrant/Projects/webspider/.env/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 187, in reraise
    raise value
  File "/home/acgtyrant/Projects/webspider/.env/lib/python3.6/site-packages/sqlalchemy/pool.py", line 1135, in _do_get
    return self._create_connection()
  File "/home/acgtyrant/Projects/webspider/.env/lib/python3.6/site-packages/sqlalchemy/pool.py", line 333, in _create_connection
    return _ConnectionRecord(self)
  File "/home/acgtyrant/Projects/webspider/.env/lib/python3.6/site-packages/sqlalchemy/pool.py", line 461, in __init__
    self.__connect(first_connect_check=True)
  File "/home/acgtyrant/Projects/webspider/.env/lib/python3.6/site-packages/sqlalchemy/pool.py", line 651, in __connect
    connection = pool._invoke_creator(self)
  File "/home/acgtyrant/Projects/webspider/.env/lib/python3.6/site-packages/sqlalchemy/engine/strategies.py", line 105, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/acgtyrant/Projects/webspider/.env/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 393, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/acgtyrant/Projects/webspider/.env/lib/python3.6/site-packages/MySQLdb/__init__.py", line 86, in Connect
    return Connection(*args, **kwargs)
  File "/home/acgtyrant/Projects/webspider/.env/lib/python3.6/site-packages/MySQLdb/connections.py", line 204, in __init__
    super(Connection, self).__init__(*args, **kwargs2)
_mysql_exceptions.OperationalError: (1049, "Unknown database 'spider'")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/acgtyrant/Projects/webspider/.env/lib/python3.6/site-packages/tornado/web.py", line 1509, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "/home/acgtyrant/Projects/webspider/app/web/handlers/keyword.py", line 14, in get
    keyword = KeywordController.get(name=keyword_name)
  File "/home/acgtyrant/Projects/webspider/app/controllers/keyword.py", line 9, in get
    return KeywordModel.get(name=name)
  File "/home/acgtyrant/Projects/webspider/app/model/keyword.py", line 17, in get
    return query.one_or_none()
  File "/home/acgtyrant/Projects/webspider/.env/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 2784, in one_or_none
    ret = list(self)
  File "/home/acgtyrant/Projects/webspider/.env/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 2855, in __iter__
    return self._execute_and_instances(context)
  File "/home/acgtyrant/Projects/webspider/.env/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 2876, in _execute_and_instances
    close_with_result=True)
  File "/home/acgtyrant/Projects/webspider/.env/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 2885, in _get_bind_args
    **kw
  File "/home/acgtyrant/Projects/webspider/.env/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 2867, in _connection_from_session
    conn = self.session.connection(**kw)
  File "/home/acgtyrant/Projects/webspider/.env/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 998, in connection
    execution_options=execution_options)
  File "/home/acgtyrant/Projects/webspider/.env/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 1003, in _connection_for_bind
    engine, execution_options)
  File "/home/acgtyrant/Projects/webspider/.env/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 403, in _connection_for_bind
    conn = bind.contextual_connect()
  File "/home/acgtyrant/Projects/webspider/.env/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 2112, in contextual_connect
    self._wrap_pool_connect(self.pool.connect, None),
  File "/home/acgtyrant/Projects/webspider/.env/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 2151, in _wrap_pool_connect
    e, dialect, self)
  File "/home/acgtyrant/Projects/webspider/.env/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1465, in _handle_dbapi_exception_noconnection
    exc_info
  File "/home/acgtyrant/Projects/webspider/.env/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 203, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/home/acgtyrant/Projects/webspider/.env/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 186, in reraise
    raise value.with_traceback(tb)
  File "/home/acgtyrant/Projects/webspider/.env/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 2147, in _wrap_pool_connect
    return fn()
  File "/home/acgtyrant/Projects/webspider/.env/lib/python3.6/site-packages/sqlalchemy/pool.py", line 387, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/acgtyrant/Projects/webspider/.env/lib/python3.6/site-packages/sqlalchemy/pool.py", line 766, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/acgtyrant/Projects/webspider/.env/lib/python3.6/site-packages/sqlalchemy/pool.py", line 516, in checkout
    rec = pool._do_get()
  File "/home/acgtyrant/Projects/webspider/.env/lib/python3.6/site-packages/sqlalchemy/pool.py", line 1138, in _do_get
    self._dec_overflow()
  File "/home/acgtyrant/Projects/webspider/.env/lib/python3.6/site-packages/sqlalchemy/util/langhelpers.py", line 66, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/home/acgtyrant/Projects/webspider/.env/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 187, in reraise
    raise value
  File "/home/acgtyrant/Projects/webspider/.env/lib/python3.6/site-packages/sqlalchemy/pool.py", line 1135, in _do_get
    return self._create_connection()
  File "/home/acgtyrant/Projects/webspider/.env/lib/python3.6/site-packages/sqlalchemy/pool.py", line 333, in _create_connection
    return _ConnectionRecord(self)
  File "/home/acgtyrant/Projects/webspider/.env/lib/python3.6/site-packages/sqlalchemy/pool.py", line 461, in __init__
    self.__connect(first_connect_check=True)
  File "/home/acgtyrant/Projects/webspider/.env/lib/python3.6/site-packages/sqlalchemy/pool.py", line 651, in __connect
    connection = pool._invoke_creator(self)
  File "/home/acgtyrant/Projects/webspider/.env/lib/python3.6/site-packages/sqlalchemy/engine/strategies.py", line 105, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/acgtyrant/Projects/webspider/.env/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 393, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/acgtyrant/Projects/webspider/.env/lib/python3.6/site-packages/MySQLdb/__init__.py", line 86, in Connect
    return Connection(*args, **kwargs)
  File "/home/acgtyrant/Projects/webspider/.env/lib/python3.6/site-packages/MySQLdb/connections.py", line 204, in __init__
    super(Connection, self).__init__(*args, **kwargs2)
sqlalchemy.exc.OperationalError: (_mysql_exceptions.OperationalError) (1049, "Unknown database 'spider'")
```

此外执行 `bin/test` 也出现了大量类似错误。

咋办！谢谢。

**Comment by GuozhuHe** [comment]
看一下错误提示啊。
`sqlalchemy.exc.OperationalError: (_mysql_exceptions.OperationalError) (1049, "Unknown database 'spider'")`
提示你找不到 `spider` 这个数据库。新建一个即可。
进入mysql: `mysql -u root`
创建数据库: `CREATE DATABASE `spider` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;`

**Comment by acgtyrant** [comment]
果然还是要手动创建数据库啊，这对不会 MySQL, 只能按 README 一步一步来的用户不友好。

现在出现了新错误：`_mysql_exceptions.ProgrammingError: (1146, "Table 'spider.keyword' doesn't exist")` 大概要新建表，我晚点研究 MySQL 命令，如果你能直接给现成的命令，或者更新项目 README 以说明，就再好不过。

**Comment by GuozhuHe** [comment]
创建数据库等的MYSQL命令不是最基础的吗。。。
表的创建语句在 `webspider/tests/schema.sql` 里都有啊。

**Comment by acgtyrant** [comment]
能不能——自动化这两个创建命令呢！比如在执行 `bin/web` 时自动执行这亮命令。
