### ISSUE TITLE
OSError: mysql_config not found

### ISSUE THREAD

**Issue by tom523** [GuozhuHe/webspider#5]
```
virtualenv -p /usr/bin/python3 env
Running virtualenv with interpreter /usr/bin/python3
Using base prefix '/usr'
New python executable in /home/tom/PycharmProjects/webspider/env/bin/python3
Not overwriting existing python script /home/tom/PycharmProjects/webspider/env/bin/python (you must use /home/tom/PycharmProjects/webspider/env/bin/python3)
Installing setuptools, pip, wheel...done.
echo "\n Use python virtual environment to install required packages......\n"

 Use python virtual environment to install required packages......

env/bin/pip install -e .
Obtaining file:///home/tom/PycharmProjects/webspider
Collecting tornado (from webspider==0.0.2)
Collecting gevent (from webspider==0.0.2)
  Using cached gevent-1.2.2-cp35-cp35m-manylinux1_x86_64.whl
Collecting gunicorn (from webspider==0.0.2)
  Using cached gunicorn-19.7.1-py2.py3-none-any.whl
Collecting ipython (from webspider==0.0.2)
  Using cached ipython-6.2.1-py3-none-any.whl
Collecting lxml (from webspider==0.0.2)
  Using cached lxml-4.1.1-cp35-cp35m-manylinux1_x86_64.whl
Collecting nose (from webspider==0.0.2)
  Using cached nose-1.3.7-py3-none-any.whl
Collecting requests (from webspider==0.0.2)
  Using cached requests-2.18.4-py2.py3-none-any.whl
Collecting coverage==4.0.3 (from webspider==0.0.2)
  Using cached coverage-4.0.3.tar.gz
Collecting flake8 (from webspider==0.0.2)
  Using cached flake8-3.5.0-py2.py3-none-any.whl
Collecting mysqlclient (from webspider==0.0.2)
  Using cached mysqlclient-1.3.12.tar.gz
    Complete output from command python setup.py egg_info:
    /bin/sh: 1: mysql_config: not found
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-iedwam3m/mysqlclient/setup.py", line 17, in <module>
        metadata, options = get_config()
      File "/tmp/pip-build-iedwam3m/mysqlclient/setup_posix.py", line 44, in get_config
        libs = mysql_config("libs_r")
      File "/tmp/pip-build-iedwam3m/mysqlclient/setup_posix.py", line 26, in mysql_config
        raise EnvironmentError("%s not found" % (mysql_config.path,))
    OSError: mysql_config not found
```

**Comment by tom523** [comment]
操作系统：
tom@tom-VirtualBox:~/PycharmProjects/webspider$ sudo lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.3 LTS
Release:	16.04
Codename:	xenial

解决方法：http://blog.csdn.net/wangtaoking1/article/details/51554959
